remove extra parts in the file-selector dialog
osumo/osumo pull request #33
Opened 2016-11-18 22:08 UTC by opadron

@manthey alerted me to some issues with the file-selector dialog that stem from the fact that a lot of extra girder widgetry was not being suppressed.  This PR should address the issues by removing these pieces with the side benefit of simplifying the dialog.  The solutions for these pieces include a combination of changing the options passed, and hacking in a custom pug template.

2016-11-18 22:08 UTC, opadron commented
@manthey try this on for size.

2016-12-08 17:29 UTC, opadron commented
@osumo/developers this needs QA.

2016-12-08 19:05 UTC, ronichoudhury commented
I tried this out just now and nothing happens when I click on the "add a
file" button. Well, the URL changes to `/#file-select`, and I see a state
change in the console, but nothing happens in the app, I should say. Maybe
I'm missing something?

On Thu, Dec 8, 2016 at 12:29 PM Omar Padron <notifications@github.com>
wrote:

> @osumo/developers <https://github.com/orgs/osumo/teams/developers> this
> needs QA.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/osumo/osumo/pull/33#issuecomment-265801233>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACxNJEeiSD8iswMD5UhSYyNSnkihX2U5ks5rGD6EgaJpZM4K2-gS>
> .
>

2016-12-08 20:46 UTC, waxlamp requested changes
After updating to a sufficiently new version of Girder, I was able to try the changes and they look very nice.

Addressing my comments is enough to get an LGTM from me. However, will this PR become moot after updating to Girder 2.0? Replicating Girder templates inside this project is not a sustainable way forward in general.

2016-12-08 20:46 UTC, ronichoudhury commented on web-external/src/components/dialog/file-selector/body.jsx
> +/* TODO(opadron): flags controlling these links should be upstreamed */
Should make this into a GitHub issue.

2016-12-08 20:46 UTC, ronichoudhury commented on web-external/src/components/dialog/file-selector/body.jsx
> +console.log(girder.views.HierarchyWidget);
Remove console log statement.

2016-12-08 20:59 UTC, opadron commented
@ronichoudhury I agree with your point.   I've made #34 to ensure that we don't keep the hacked templates after migrating to Girder 2.0, which should also fix several other minor issues.

2016-12-08 20:59 UTC, opadron commented on web-external/src/components/dialog/file-selector/body.jsx
> +/* TODO(opadron): flags controlling these links should be upstreamed */
This TODO is already TODONE. :tada:

2016-12-08 21:00 UTC, opadron commented on web-external/src/components/dialog/file-selector/body.jsx
> +/* TODO(opadron): flags controlling these links should be upstreamed */
see girder/girder#1688

2016-12-08 21:02 UTC, ronichoudhury commented on web-external/src/components/dialog/file-selector/body.jsx
> +/* TODO(opadron): flags controlling these links should be upstreamed */
Can we remove the TODO from the comment then? Or maybe change it to a reference to the upstream fix?

2016-12-08 21:38 UTC, waxlamp approved these changes

2016-12-08 21:39 UTC, merged

2016-12-08 21:39 UTC, opadron commented
Thanks, @ronichoudhury.