Anonymous login
osumo/osumo pull request #46
Opened 2017-04-04 18:59 UTC by ronichoudhury

This adds the "anonymous login" functionality. Essentially:
- Any time you log out of the app explicitly, the system implicitly logs in a special user, but makes the UI look like no one is logged in. This lets people use the application without first having to create an account.
- The username and password have to be supplied via a pair of environment variables - `OSUMO_ANON_USER` and `OSUMO_ANON_PASSWORD` - at Girder launch time. Failing to supply these results in a fatal error, and the osumo plugin will not load.

2017-04-05 21:11 UTC, ronichoudhury commented
@opadron this is ready for review.

2017-04-06 15:27 UTC, opadron requested changes
LGTM after that catch is moved up.

2017-04-06 15:27 UTC, opadron commented on web_client/actions.jsx
>            )
It just occurred to me that we'd want to move the catch up a few calls in the chain.  We wouldn't want to try to anonymously log in if something went wrong with the dialog closing, for example.

2017-04-10 19:35 UTC, opadron commented on web_client/actions.jsx
>            )
I'll elaborate even further on this point:

What we want, *precisely*, is for a catch handler to handle the case where the normal `rest.login()` call fails.  In this case, the app needs to relog as the anonymous user.  The important detail is that we don't want this catch handler to fire in *any* other scenario.

To accomplish this, the promise handler that returns `rest.login(...)` (line 539) should be rewritten to return a promise subchain, with `rest.login(...)` at the head, and the catch handler being the only two links in the chain.

```javascript
return (
  rest
    .logout()
    .then(() => (
      rest.login(login, password)
        .catch(
          ({ responseJSON: { message } }) => (
            ...
          )
        )
    ))
    .then((user) => dispatch(...))
    ...
)
```

Please excuse any typos in the code above.  It has not been tested.

2017-04-10 19:37 UTC, opadron commented on web_client/actions.jsx
>            )
I also just realized that the catch handler needs to return `Promise.reject(arg)` where arg is the argument passed to it.  This also needs to be done to propagate the error to the parent promise chain.

2017-04-10 21:18 UTC, ronichoudhury commented on web_client/actions.jsx
>            )
@opadron could you take a look at b492118? Not sure I did it correctly.

2017-04-11 13:34 UTC, opadron approved these changes
LGTM

2017-04-11 13:36 UTC, merged

2017-04-11 13:48 UTC, jeffbaumes commented
🍰 🎉