Igpse feature select UI + Backend
osumo/osumo pull request #56
Opened 2017-04-20 23:00 UTC by opadron

Adds the UI components and backend scripts to support the feature selection portion of the iGPSe workflow.

Note that currently the main iGPSe clustering and/or survival plot generating steps may fail due to a known issue that will be addressed in an upcoming PR.

2017-04-24 19:41 UTC, waxlamp requested changes
Feature works well with a good testing workflow. Check out my style/content suggestions and let me know what you think @opadron.

2017-04-24 19:41 UTC, waxlamp commented on server/task_specs/igpse-survival-plot.r
> +
Remove blank line

2017-04-24 19:41 UTC, waxlamp commented on server/task_specs/igpse-survival-plot.r
> +
Remove blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-feature-selection.jsx
> +const D = store.dispatch.bind(store);
Use `dispatch` in place of `D`. At the very least, don't use a capitalized variable name.

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-input.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-input.jsx
> +  Promise.resolve(payload = data)
This style of expression is a generally known "code smell". It might be better to have `payload = data;` on its own line, then change this to `Promise.resolve(payload);`, just to avoid possible confusion at the anti-pattern, etc.

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-input.jsx
> +  // .then(() => Promise.all([
Can this commented-out code be removed?

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-main.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-main.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-main.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-subset-selection.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-survival-plot.jsx
> +
blank line

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-feature-selection.jsx
> +const SUGGESTION_DELAY_MILLISECONDS = 100;
So if the use of `delayedSemaphore()` here is solely to provide debouncing for the autosuggest feature, I'd seriously take a look at either `_.debounce()` or else just implement debouncing directly in a utility function. It's a common enough idiom that it will make this stretch of code far easier to understand.

2017-04-24 19:41 UTC, waxlamp commented on web_client/analysis-modules/igpse-feature-selection.jsx
> +const SUGGESTION_DELAY_MILLISECONDS = 100;
But probably just use a library function like `_.debouce()` :-D

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +  (
remove parens

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +    .forEach((e) => {
unbreak line

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +          (
remove parens

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +            [state.currentText].concat(
Put all of this on a single line

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +              s
Join this to the next line.

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +            .map((s) => (
Remove parens

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +            .filter(({ length }) => length)
This seems confusing. Is the destructuring argument meant to take advantage of the fact that strings and arrays have a static `length` property? I would change this to be a little bit less opaque:

```javascript
.filter(s => s.length > 0)
```

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +    return (
Remove parentheses

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +                // width: 200,
Why are these commented out?

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +                // marginRight: 1,
Why are these commented out?

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/index.jsx
> +        result = (
Remove parentheses and unbreak line.

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +                transitioning
This looks a lot like it could simplified to `transitioning === singleMode ? 'Multi' : 'Search"` but that may not be any less confusing.

2017-04-24 19:41 UTC, ronichoudhury commented on server/task_specs/feature-extract.py
> +        extractor = (ColumnExtractor if extract_columns else RowExtractor)
Can this line, line 30, and line 35 all be factored out into a single, hoisted line?

2017-04-24 19:41 UTC, ronichoudhury commented on server/task_specs/feature-slice.py
> +            num -= sum(1 if c == char else 0 for c in sample)
Could also be

```python
num -= len(filter(lambda c: c == char, sample))
```

but not sure if that's any simpler to understand.

2017-04-24 19:41 UTC, ronichoudhury commented on server/task_specs/feature-slice.py
> +def read_until(f, char, num=1):
Write tests for this function

2017-04-24 19:41 UTC, ronichoudhury commented on server/task_specs/feature-slice.yml
> +
remove blank line

2017-04-24 19:41 UTC, ronichoudhury commented on server/ui_specs/igpse-subset-selection-a.yml
> +
remove blank line

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/analysis-modules/igpse-feature-selection.jsx
> +    igpse.registerAction('featureSelection', 'process'           ),
remove excess spaces

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/analysis-modules/igpse-feature-selection.jsx
> +    igpse.registerAction('featureSelection', 'mrnaFeatureUpdate' ),
remove excess spaces

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/analysis-modules/igpse-lib.jsx
> +
blank line

2017-04-24 19:41 UTC, ronichoudhury commented on web_client/analysis-modules/igpse-lib.jsx
> +    window.G = this;
Is this a debugging statement meant to be deleted later?

2017-04-25 15:25 UTC, opadron commented on server/task_specs/feature-extract.py
> +        extractor = (ColumnExtractor if extract_columns else RowExtractor)
Yes!  Good catch. :+1:

2017-04-25 15:26 UTC, opadron commented on web_client/analysis-modules/igpse-lib.jsx
> +    window.G = this;
You are absolutely right!  I'll scratch that.

2017-04-25 15:29 UTC, opadron commented on web_client/analysis-modules/igpse-lib.jsx
> +    window.G = this;
But I gotta ask: the table above this line should have been "fixed" per the linter's suggestion that the extra whitespace be removed.  I'm not seeing it reflected in this version of the file?

2017-04-25 17:50 UTC, opadron commented
@ronichoudhury PTAL.  I suspect you will be pleased with my recent additions! :)

2017-04-25 20:02 UTC, waxlamp requested changes
Looks good! Just one comment about parentheses.

2017-04-25 20:02 UTC, ronichoudhury commented on .eslintrc.json
> +
blank lines :)

2017-04-25 20:02 UTC, ronichoudhury commented on web_client/components/body/analysis/element/feature-selection.jsx
> +    .map((s) => (s.split(' ').filter(isNonEmpty).join(' ')))
Remove parentheses around `s.split...`

2017-04-25 20:02 UTC, opadron commented on .eslintrc.json
> +
Argh! Haha

2017-04-25 20:04 UTC, waxlamp approved these changes

2017-04-25 20:08 UTC, merged